CREATE TABLE `product type` (
    type_code int PRIMARY KEY,
    category VARCHAR(50),
    gender VARCHAR(50),
    kid BOOLEAN,
    sports_type VARCHAR(50)
);

INSERT INTO `product type` (type_code, category, gender, kid, sports_type) VALUES
('01', 'Clothing', 'Women', false, 'Baseball'),
('02', 'Clothing', 'Women', false, 'Basketball'),
('03', 'Clothing', 'Women', false, 'Cycling'),
('04', 'Clothing', 'Women', false, 'Football'),
('05', 'Clothing', 'Women', false, 'Golf'),
('06', 'Clothing', 'Women', false, 'Hiking'),
('07', 'Clothing', 'Women', false, 'Hockey'),
('08', 'Clothing', 'Women', false, 'Outdoor'),
('09', 'Clothing', 'Women', false, 'Running'),
('10', 'Clothing', 'Women', false, 'Soccer'),
('11', 'Clothing', 'Women', false, 'Tennis'),
('12', 'Clothing', 'Women', false, 'Workout & Gym'),
('13', 'Clothing', 'Women', false, 'Yoga'),
('14', 'Shoes', 'Women', false, 'Cycling'),
('15', 'Shoes', 'Women', false, 'Walking'),
('16', 'Shoes', 'Women', false, 'Outdoor'),
('17', 'Shoes', 'Women', false, 'Running'),
('18', 'Shoes', 'Women', false, 'Basketball'),
('19', 'Shoes', 'Women', false, 'Tennis'),
('20', 'Shoes', 'Women', false, 'Golf'),
('21', 'Shoes', 'Women', false, 'Workout & Gym'),
('22', 'Accessories', 'Women', false, 'Running'),
('23', 'Accessories', 'Women', false, 'Workout & Gym'),
('24', 'Clothing', 'Man', false, 'Baseball'),
('25', 'Clothing', 'Man', false, 'Basketball'),
('26', 'Clothing', 'Man', false, 'Cycling'),
('27', 'Clothing', 'Man', false, 'Football'),
('28', 'Clothing', 'Man', false, 'Golf'),
('29', 'Clothing', 'Man', false, 'Hiking'),
('30', 'Clothing', 'Man', false, 'Hockey'),
('31', 'Clothing', 'Man', false, 'Outdoor'),
('32', 'Clothing', 'Man', false, 'Running'),
('33', 'Clothing', 'Man', false, 'Soccer'),
('34', 'Clothing', 'Women', false, 'Tennis'),
('35', 'Clothing', 'Man', false, 'Workout & Gym'),
('36', 'Clothing', 'Man', false, 'Yoga'),
('37', 'Shoes', 'Man', false, 'Cycling'),
('38', 'Shoes', 'Man', false, 'Walking'),
('39', 'Shoes', 'Man', false, 'Outdoor'),
('40', 'Shoes', 'Man', false, 'Running'),
('41', 'Shoes', 'Man', false, 'Basketball'),
('42', 'Shoes', 'Man', false, 'Tennis'),
('43', 'Shoes', 'Man', false, 'Golf'),
('44', 'Shoes', 'Man', false, 'Workout & Gym'),
('45', 'Accessories', 'Man', false, 'Running'),
('46', 'Accessories', 'Man', false, 'Workout & Gym'),
('47', 'Clothing', 'Women', true, 'Outdoor'),
('48', 'Clothing', 'Women', true, 'Running'),
('49', 'Clothing', 'Women', true, 'Workout & Gym'),
('50', 'Shoes', 'Women', true, 'Walking'),
('51', 'Shoes', 'Women', true, 'Outdoor'),
('52', 'Shoes', 'Women', true, 'Running'),
('53', 'Clothing', 'Man', true, 'Outdoor'),
('54', 'Clothing', 'Man', true, 'Running'),
('55', 'Clothing', 'Man', true, 'Workout & Gym'),
('56', 'Shoes', 'Man', true, 'Walking'),
('57', 'Shoes', 'Man', true, 'Outdoor'),
('58', 'Shoes', 'Man', true, 'Running');